### ISSUE TITLE
Training is slow and some errors (perhaps)

### ISSUE THREAD

**Issue by Zth9730** [Jamie-Stirling/RetNet#4]
#### For the first time, there seems to be a problem in the code, and it seems that we need to change [here](https://github.com/Jamie-Stirling/RetNet/blob/main/src/retention.py#L153) to

```
return (self.swish(X @ self.W_G.to(self.complex_type)) + Y) @ self.W_O.to(self.complex_type)
```

**Comment by Jamie-Stirling** [comment]
Hi, thanks for raising this issue. Please could you provide more context on the situation that gives unstable memory usage? Is it the parallel or recurrent paradigm?

Thanks for pointing out the fix to MultiScaleRetention, I've now made a commit which fixes this.

**Comment by Zth9730** [comment]
I'm using parallel forward and the utilization rate of gpus jump from 1%-100% and cycle.  ┭┮﹏┭┮
Of course the normal state should be stabilized above 90% (at least most of the time).
May I ask if your gpus utilization is consistently high when using retnet for actual training?
Thank you! 😊

**Comment by Jamie-Stirling** [comment]
Thanks for raising this issue. I'll look into this.

**Comment by tang-ed** [comment]
Due to the use of custom algorithms, which are implemented in Python, the speed is very slow. Pytorch uses algorithms implemented at the bottom of C++.

**Comment by Jamie-Stirling** [comment]
> Due to the use of custom algorithms, which are implemented in Python, the speed is very slow. Pytorch uses algorithms implemented at the bottom of C++.

Agreed, please see [this issue](https://github.com/Jamie-Stirling/RetNet/issues/5). A real-valued implementation will allow greater use of PyTorch built-ins. In the meantime, hopefully the complex-valued implementation can be used for building intuition about how RetNet works.

**Comment by Jamie-Stirling** [comment]
The real-valued version has now been implemented and makes better use of PyTorch's built-in functions. This is now the default implementation in `/src/`. The aforementioned error has also been fixed.
